#!/usr/bin/env python3
"""
pose_teacher.py — Interactive arm pose teaching tool for RECLAIM

Connects to Teensy running arm_commander firmware over serial.
Lets you:
  1. Nudge individual joints to desired positions
  2. Save the current position as a named pose
  3. Go to any saved pose (smooth quintic motion)
  4. Find safe angle ranges for each joint
  5. Export all poses to poses.yaml

Run on MIC-711:
  python3 pose_teacher.py

Requires: pyserial, pyyaml
  pip install pyserial pyyaml
"""

import serial
import yaml
import time
import sys
import os
import readline  # enables arrow keys and history in input()

# ── Config ────────────────────────────────────────────────────────────────────

SERIAL_PORT = "/dev/ttyACM0"
BAUD_RATE = 115200
TIMEOUT = 2.0

JOINT_NAMES = ["base", "shoulder", "elbow", "wrist_pitch", "wrist_rotate", "gripper"]
POSES_FILE = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "config", "poses.yaml")

# ── Serial helpers ────────────────────────────────────────────────────────────

def send_cmd(ser, cmd):
    """Send command and return all response lines until timeout."""
    ser.reset_input_buffer()
    ser.write((cmd + "\n").encode())
    time.sleep(0.05)
    lines = []
    deadline = time.time() + 1.0
    while time.time() < deadline:
        if ser.in_waiting:
            line = ser.readline().decode().strip()
            if line:
                lines.append(line)
                deadline = time.time() + 0.3  # extend deadline while data flowing
        else:
            time.sleep(0.02)
    return lines


def get_angles(ser):
    """Get current joint angles from Teensy."""
    lines = send_cmd(ser, "GET")
    for line in lines:
        if line.startswith("ANGLES"):
            parts = line.split()[1:]
            if len(parts) == 6:
                return [int(x) for x in parts]
    return None


def wait_for_done(ser, timeout=10):
    """Wait for DONE response after a move command."""
    deadline = time.time() + timeout
    while time.time() < deadline:
        if ser.in_waiting:
            line = ser.readline().decode().strip()
            if line == "DONE":
                return True
            if line.startswith("ANGLES"):
                continue
        time.sleep(0.02)
    return False

# ── Poses file I/O ────────────────────────────────────────────────────────────

def load_poses():
    """Load poses from YAML file."""
    if os.path.exists(POSES_FILE):
        with open(POSES_FILE, "r") as f:
            data = yaml.safe_load(f) or {}
        return data.get("poses", {})
    return {}


def save_poses(poses):
    """Save poses to YAML file."""
    os.makedirs(os.path.dirname(POSES_FILE), exist_ok=True)
    data = {
        "poses": poses,
        "joint_order": JOINT_NAMES,
        "notes": "Generated by pose_teacher.py. Angles in degrees (0-180)."
    }
    with open(POSES_FILE, "w") as f:
        yaml.dump(data, f, default_flow_style=False, sort_keys=False)
    print(f"  Saved to {POSES_FILE}")

# ── Interactive commands ──────────────────────────────────────────────────────

def cmd_nudge(ser):
    """Nudge a single joint by N degrees."""
    print("\n  Joints: 1=Base 2=Shoulder 3=Elbow 4=WristPitch 5=WristRotate 6=Gripper")
    try:
        joint = int(input("  Joint (1-6): "))
        deg = int(input("  Degrees (+/-): "))
    except (ValueError, EOFError):
        print("  Cancelled.")
        return
    lines = send_cmd(ser, f"NUDGE {joint} {deg}")
    for line in lines:
        print(f"  {line}")


def cmd_set(ser):
    """Set all joint angles at once."""
    print("\n  Enter 6 angles separated by spaces (base shoulder elbow wpitch wrotate gripper)")
    try:
        raw = input("  Angles: ").strip()
        duration = input("  Duration ms (default 1000): ").strip()
    except (ValueError, EOFError):
        print("  Cancelled.")
        return
    if not duration:
        duration = "1000"
    cmd = f"SET {raw} {duration}"
    lines = send_cmd(ser, cmd)
    for line in lines:
        print(f"  {line}")
    wait_for_done(ser)


def cmd_teach(ser, poses):
    """Save current position as a named pose."""
    angles = get_angles(ser)
    if angles is None:
        print("  ERROR: Could not read angles from Teensy")
        return

    print(f"\n  Current angles: {angles}")
    print(f"  ({', '.join(f'{JOINT_NAMES[i]}={angles[i]}' for i in range(6))})")

    try:
        name = input("  Pose name (e.g. home, bin1_drop): ").strip()
    except EOFError:
        return

    if not name:
        print("  Cancelled.")
        return

    poses[name] = {JOINT_NAMES[i]: angles[i] for i in range(6)}
    save_poses(poses)
    print(f"  Saved pose '{name}': {angles}")


def cmd_goto(ser, poses):
    """Go to a saved pose."""
    if not poses:
        print("  No saved poses. Use 'teach' to save some first.")
        return

    print("\n  Available poses:")
    for name, joints in poses.items():
        vals = [joints.get(j, 90) for j in JOINT_NAMES]
        print(f"    {name}: {vals}")

    try:
        name = input("  Pose name: ").strip()
        duration = input("  Duration ms (default 1500): ").strip()
    except EOFError:
        return

    if name not in poses:
        print(f"  Unknown pose '{name}'")
        return

    if not duration:
        duration = "1500"

    joints = poses[name]
    angles = [joints.get(j, 90) for j in JOINT_NAMES]
    angles_str = " ".join(str(a) for a in angles)
    cmd = f"SET {angles_str} {duration}"

    print(f"  Moving to '{name}': {angles} over {duration}ms...")
    lines = send_cmd(ser, cmd)
    for line in lines:
        print(f"  {line}")
    wait_for_done(ser)


def cmd_sequence(ser, poses):
    """Run a sequence of poses (e.g., pick and place cycle)."""
    if not poses:
        print("  No saved poses.")
        return

    print("\n  Available poses:", ", ".join(poses.keys()))
    try:
        raw = input("  Sequence (space-separated pose names): ").strip()
        duration = input("  Duration per move ms (default 1500): ").strip()
    except EOFError:
        return

    if not duration:
        duration = "1500"

    names = raw.split()
    for name in names:
        if name not in poses:
            print(f"  Unknown pose '{name}', stopping.")
            return

    print(f"\n  Running sequence: {' -> '.join(names)}")
    for i, name in enumerate(names):
        joints = poses[name]
        angles = [joints.get(j, 90) for j in JOINT_NAMES]
        angles_str = " ".join(str(a) for a in angles)

        print(f"\n  [{i+1}/{len(names)}] -> {name}: {angles}")
        send_cmd(ser, f"SET {angles_str} {duration}")
        wait_for_done(ser, timeout=int(duration) // 1000 + 5)
        time.sleep(0.3)  # brief pause between poses

    print("\n  Sequence complete.")


def cmd_find_limits(ser):
    """Interactive tool to find safe angle ranges for each joint."""
    print("\n  === FINDING SAFE LIMITS ===")
    print("  For each joint, we'll slowly move toward 0 and toward 180.")
    print("  Press Enter to step by 5 degrees, 'q' to set the limit.\n")

    limits = {}
    for idx in range(6):
        name = JOINT_NAMES[idx]
        joint_num = idx + 1
        print(f"\n  --- Joint {joint_num}: {name} ---")

        # Center first
        send_cmd(ser, f"NUDGE {joint_num} {90 - int(get_angles(ser)[idx])}")
        time.sleep(0.5)

        # Find minimum
        print(f"  Finding MINIMUM (stepping toward 0)...")
        current = get_angles(ser)[idx]
        while current > 0:
            try:
                resp = input(f"    Current: {current}. Enter to step -5, or type a number, or 'q' to stop: ").strip()
            except EOFError:
                break
            if resp.lower() == 'q':
                break
            step = -5
            if resp:
                try:
                    step = int(resp)
                except ValueError:
                    break
            send_cmd(ser, f"NUDGE {joint_num} {step}")
            time.sleep(0.3)
            angles = get_angles(ser)
            if angles:
                current = angles[idx]

        safe_min = current
        print(f"    Minimum set to: {safe_min}")

        # Recenter
        send_cmd(ser, f"NUDGE {joint_num} {90 - current}")
        time.sleep(0.5)

        # Find maximum
        print(f"  Finding MAXIMUM (stepping toward 180)...")
        current = get_angles(ser)[idx]
        while current < 180:
            try:
                resp = input(f"    Current: {current}. Enter to step +5, or type a number, or 'q' to stop: ").strip()
            except EOFError:
                break
            if resp.lower() == 'q':
                break
            step = 5
            if resp:
                try:
                    step = int(resp)
                except ValueError:
                    break
            send_cmd(ser, f"NUDGE {joint_num} {step}")
            time.sleep(0.3)
            angles = get_angles(ser)
            if angles:
                current = angles[idx]

        safe_max = current
        print(f"    Maximum set to: {safe_max}")

        limits[name] = {"min": safe_min, "max": safe_max}
        print(f"    {name}: {safe_min} - {safe_max}")

        # Return to center
        send_cmd(ser, f"NUDGE {joint_num} {90 - current}")
        time.sleep(0.5)

    print("\n  === SAFE LIMITS FOUND ===")
    for name, lim in limits.items():
        print(f"    {name}: {lim['min']} - {lim['max']}")

    # Save limits
    limits_file = os.path.join(os.path.dirname(POSES_FILE), "joint_limits.yaml")
    os.makedirs(os.path.dirname(limits_file), exist_ok=True)
    with open(limits_file, "w") as f:
        yaml.dump({"joint_limits": limits}, f, default_flow_style=False, sort_keys=False)
    print(f"\n  Saved to {limits_file}")
    print("  Copy these into arm_commander firmware SAFE_MIN/SAFE_MAX arrays.")


def cmd_list(poses):
    """List all saved poses."""
    if not poses:
        print("  No saved poses yet.")
        return
    print("\n  Saved poses:")
    for name, joints in poses.items():
        vals = [joints.get(j, 90) for j in JOINT_NAMES]
        print(f"    {name}: {vals}")


def cmd_delete(poses):
    """Delete a saved pose."""
    if not poses:
        print("  No saved poses.")
        return
    cmd_list(poses)
    try:
        name = input("  Pose to delete: ").strip()
    except EOFError:
        return
    if name in poses:
        del poses[name]
        save_poses(poses)
        print(f"  Deleted '{name}'")
    else:
        print(f"  Unknown pose '{name}'")

# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    print("=" * 50)
    print("  RECLAIM Pose Teacher")
    print("=" * 50)

    # Connect to Teensy
    print(f"\n  Connecting to {SERIAL_PORT} at {BAUD_RATE}...")
    try:
        ser = serial.Serial(SERIAL_PORT, BAUD_RATE, timeout=TIMEOUT)
    except serial.SerialException as e:
        print(f"  ERROR: {e}")
        print(f"  Make sure Teensy is connected and run: sudo chmod 666 {SERIAL_PORT}")
        sys.exit(1)

    time.sleep(2)  # wait for Teensy to reset after serial open
    ser.reset_input_buffer()

    # Read startup messages
    startup = send_cmd(ser, "HELP")
    for line in startup:
        if "ARM_COMMANDER" in line:
            print(f"  Connected: {line}")
            break
    else:
        print("  WARNING: Didn't get ARM_COMMANDER banner. Is the right firmware flashed?")

    # Load existing poses
    poses = load_poses()
    if poses:
        print(f"  Loaded {len(poses)} saved poses from {POSES_FILE}")

    # Command loop
    print("\n  Commands:")
    print("    nudge    - Move one joint by N degrees")
    print("    set      - Set all 6 joint angles")
    print("    get      - Print current angles")
    print("    teach    - Save current position as named pose")
    print("    goto     - Move to a saved pose")
    print("    seq      - Run a sequence of saved poses")
    print("    list     - List all saved poses")
    print("    delete   - Delete a saved pose")
    print("    limits   - Find safe angle ranges for each joint")
    print("    home     - Go to home position")
    print("    raw      - Send raw command to Teensy")
    print("    quit     - Exit")
    print()

    while True:
        try:
            cmd = input("pose> ").strip().lower()
        except (EOFError, KeyboardInterrupt):
            break

        if cmd in ("quit", "exit", "q"):
            break
        elif cmd == "nudge":
            cmd_nudge(ser)
        elif cmd == "set":
            cmd_set(ser)
        elif cmd == "get":
            angles = get_angles(ser)
            if angles:
                print(f"  {angles}")
                print(f"  ({', '.join(f'{JOINT_NAMES[i]}={angles[i]}' for i in range(6))})")
        elif cmd == "teach":
            cmd_teach(ser, poses)
        elif cmd == "goto":
            cmd_goto(ser, poses)
        elif cmd == "seq":
            cmd_sequence(ser, poses)
        elif cmd == "list":
            cmd_list(poses)
        elif cmd == "delete":
            cmd_delete(poses)
        elif cmd == "limits":
            cmd_find_limits(ser)
        elif cmd == "home":
            send_cmd(ser, "HOME")
            wait_for_done(ser)
            print("  Home.")
        elif cmd == "raw":
            try:
                raw = input("  Command: ").strip()
            except EOFError:
                continue
            lines = send_cmd(ser, raw)
            for line in lines:
                print(f"  {line}")
        elif cmd == "":
            continue
        else:
            print(f"  Unknown command '{cmd}'. Type a command or 'quit'.")

    ser.close()
    print("\n  Disconnected.")


if __name__ == "__main__":
    main()
