[env:auto_test]
platform = teensy
board = teensy41
framework = arduino
monitor_speed = 115200
upload_protocol = teensy-cli
build_src_filter = +<main.cpp>

[env:manual]
platform = teensy
board = teensy41
framework = arduino
monitor_speed = 115200
upload_protocol = teensy-cli
build_src_filter = +<manual_control.cpp>

[env:dual_test]
platform = teensy
board = teensy41
framework = arduino
monitor_speed = 115200
upload_protocol = teensy-cli
build_src_filter = +<dual_motor_test.cpp>
